Repository FESP-8/final-project, pull requests merged in 2023-11, with the labels that each got.

#8 📝 docs: pr 및 issue 템플릿 설정
  .github/ISSUE_TEMPLATE/✅-todos.md
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/❗-bug-report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#10 📝 docs: gitmessage 설정
  .gitmessage
Labels: ⚙️설정

#11 ⚙️ config: 개발환경 초기 세팅
  .eslintrc.json
  .gitmessage
  .prettierrc
  package-lock.json
  package.json
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/components/ErrorComponent.tsx
  src/components/detail/DetailHeader.tsx
  src/components/detail/index.ts
  src/components/index.ts
  src/components/main/MainHeader.tsx
  src/components/main/index.ts
  src/constants/errorText.ts
  src/constants/index.ts
  src/index.css
  src/index.tsx
  src/logo.svg
  src/pages/DetailPage.tsx
  src/pages/Layout.tsx
  src/pages/MainPage.tsx
  src/pages/Router.tsx
  src/pages/index.ts
  src/reportWebVitals.ts
Labels: ⚙️설정

#12 📝 docs: gitmessage 재설정
  .gitmessage
Labels: ⚙️설정

#15 ⚙️ config: styled-component 초기 세팅 완료 #14
  craco.config.js
  package-lock.json
  package.json
  src/components/common/CommonFooter.tsx
  src/components/common/CommonHeader.tsx
  src/components/common/CommonLogo.tsx
  src/components/common/CommonSocial.tsx
  src/components/common/index.ts
  src/components/main/MainContent.tsx
  src/components/main/MainThumbnail.tsx
  src/components/main/index.ts
  src/constants/footerText.ts
  src/constants/index.ts
  src/index.tsx
  src/pages/Layout.tsx
  src/pages/MainPage.tsx
  src/styles/global.ts
  src/styles/index.ts
  src/styles/theme.ts
  src/types/index.ts
  src/types/logo.ts
  src/types/video.ts
  tsconfig.paths.json
Labels: ⚙️설정

#18 ✨ feat: 메인페이지 콘텐츠 기능 및 레이아웃 구현 완료 #17
  src/components/common/CommonFooter.tsx
  src/components/common/CommonScrollAnchor.tsx
  src/components/common/index.ts
  src/components/main/MainContent.tsx
  src/constants/footerText.ts
  src/pages/MainPage.tsx
  src/styles/global.ts
Labels: ✨기능 추가

#21 ✨ feat: 상세 페이지 구현
  .prettierrc
  craco.config.js
  package-lock.json
  package.json
  public/logo192.png
  public/logo512.png
  src/components/common/CommonFooter.tsx
  src/components/common/CommonScrollAnchor.tsx
  src/components/common/CommonShare.tsx
  src/components/common/CommonWatchList.tsx
  src/components/common/index.ts
  src/components/detail/DetailContent.tsx
  src/components/detail/DetailHeader.tsx
  src/components/detail/DetailMainContent.tsx
  src/components/detail/DetailRelatedList.tsx
  src/components/detail/index.ts
  src/components/main/MainContent.tsx
  src/components/main/MainThumbnail.tsx
  src/constants/footerText.ts
  src/hooks/index.ts
  src/hooks/useSwipe.ts
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/pages/Router.tsx
  src/styles/global.ts
  src/styles/theme.ts
  src/types/video.ts
  src/utils/formatTime.ts
  src/utils/index.ts
  tsconfig.paths.json
Labels: ✨기능 추가, 🎨HTML/CSS

#23 ✨ feat: 상세 페이지 구현
  .prettierrc
  craco.config.js
  package-lock.json
  package.json
  public/logo192.png
  public/logo512.png
  src/components/common/CommonFooter.tsx
  src/components/common/CommonScrollAnchor.tsx
  src/components/common/CommonShare.tsx
  src/components/common/CommonWatchList.tsx
  src/components/common/index.ts
  src/components/detail/DetailContent.tsx
  src/components/detail/DetailHeader.tsx
  src/components/detail/DetailMainContent.tsx
  src/components/detail/DetailRelatedList.tsx
  src/components/detail/index.ts
  src/components/main/MainContent.tsx
  src/components/main/MainThumbnail.tsx
  src/constants/footerText.ts
  src/hooks/index.ts
  src/hooks/useSwipe.ts
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/pages/Router.tsx
  src/styles/global.ts
  src/styles/theme.ts
  src/types/video.ts
  src/utils/formatTime.ts
  src/utils/index.ts
  tsconfig.paths.json
Labels: ✨기능 추가, 🎨HTML/CSS

#28 🎨 style: 레이아웃 추가 및 수정 및 코드 정렬 #27
  src/components/common/CommonFooter.tsx
  src/components/common/CommonHeader.tsx
  src/components/common/CommonLogo.tsx
  src/components/common/CommonPlayLogo.tsx
  src/components/common/CommonScrollAnchor.tsx
  src/components/common/CommonSearch.tsx
  src/components/common/CommonXBtn.tsx
  src/components/common/index.ts
  src/components/main/MainContent.tsx
  src/components/main/MainHeader.tsx
  src/components/main/MainThumbnail.tsx
  src/components/main/index.ts
  src/pages/Layout.tsx
  src/pages/MainPage.tsx
  src/pages/Router.tsx
  src/styles/global.ts
  src/types/video.ts
Labels: ✨기능 추가

#29 메인 페이지 병합
  src/components/common/CommonFooter.tsx
  src/components/common/CommonHeader.tsx
  src/components/common/CommonLogo.tsx
  src/components/common/CommonPlayLogo.tsx
  src/components/common/CommonScrollAnchor.tsx
  src/components/common/CommonSearch.tsx
  src/components/common/CommonXBtn.tsx
  src/components/common/index.ts
  src/components/main/MainContent.tsx
  src/components/main/MainHeader.tsx
  src/components/main/MainThumbnail.tsx
  src/components/main/index.ts
  src/pages/Layout.tsx
  src/pages/MainPage.tsx
  src/pages/Router.tsx
  src/styles/global.ts
  src/types/video.ts
Labels: ✨기능 추가

#32 ♻️ refactor: detailPage 파일 로딩 방식 수정
  src/components/common/CommonHeader.tsx
  src/pages/DetailPage.tsx
  src/pages/Router.tsx
Labels: ♻️리팩토링

#33 ✨ feat: 기능 구현 전 페이지 완료
  craco.config.js
  src/components/common/CommonFooter.tsx
  src/components/common/CommonHeader.tsx
  src/components/common/CommonLogo.tsx
  src/components/index.ts
  src/components/main/MainContent.tsx
  src/components/main/MainThumbnail.tsx
  src/components/search/SearchContent.tsx
  src/components/search/index.ts
  src/hooks/index.ts
  src/hooks/useDebounce.ts
  src/pages/MainPage.tsx
  src/pages/Router.tsx
  src/styles/contentStyle.ts
  src/styles/index.ts
  tsconfig.paths.json
Labels: ✨기능 추가

#35 ♻️ refactor: 초기 로딩 개선 및 일부 기능 및 경로 수정
  craco.config.js
  src/components/ErrorComponent.tsx
  src/components/common/CommonFooter.tsx
  src/components/common/CommonHeader.tsx
  src/components/common/index.ts
  src/components/detail/DetailMainContent.tsx
  src/components/detail/DetailRelatedList.tsx
  src/components/icons/CommonLogo.tsx
  src/components/icons/CommonPlayLogo.tsx
  src/components/icons/CommonScrollAnchor.tsx
  src/components/icons/CommonSearch.tsx
  src/components/icons/CommonShare.tsx
  src/components/icons/CommonSocial.tsx
  src/components/icons/CommonWatchList.tsx
  src/components/icons/CommonXBtn.tsx
  src/components/icons/index.ts
  src/components/index.ts
  src/components/main/MainContent.tsx
  src/components/main/MainThumbnail.tsx
  src/hooks/useSwipe.ts
  src/pages/MainPage.tsx
  src/pages/Router.tsx
  src/styles/contentStyle.ts
  src/types/index.ts
  src/types/listSwipe.ts
  tsconfig.paths.json
Labels: ♻️리팩토링

#37 🎨 style: videoCard 호버 시 애니메이팅 및 버튼 아이콘 수정
  src/components/common/CommonTopButton.tsx
  src/components/common/index.ts
  src/components/detail/DetailMainContent.tsx
  src/components/detail/DetailRelatedList.tsx
  src/components/icons/CommonArrow.tsx
  src/components/icons/CommonLogo.tsx
  src/components/icons/CommonScrollAnchor.tsx
  src/components/icons/CommonShare.tsx
  src/components/icons/CommonSocial.tsx
  src/components/icons/CommonWatchList.tsx
  src/components/icons/index.ts
  src/components/main/ContentCard.tsx
  src/components/main/MainContent.tsx
  src/components/main/MainThumbnail.tsx
  src/components/main/index.ts
  src/components/search/SearchContent.tsx
  src/pages/MainPage.tsx
  src/styles/contentStyle.ts
  src/styles/theme.ts
  src/types/button.ts
  src/types/index.ts
  src/types/logo.ts
Labels: 🎨HTML/CSS, ♻️리팩토링

#41 ✨feat: 검색 기능 추가 및 수정
  src/components/common/CommonHeader.tsx
  src/components/detail/DetailMainContent.tsx
  src/components/index.ts
  src/components/main/MainThumbnail.tsx
  src/components/search/IsNotSearched.tsx
  src/components/search/index.ts
  src/constants/index.ts
  src/constants/isNotSearchText.ts
  src/pages/MainPage.tsx
  src/pages/Router.tsx
  src/pages/SearchPage.tsx
  src/pages/index.ts
  src/styles/contentStyle.ts
Labels: ✨기능 추가

#42 ⚙️ config: supabase 설치 및 초기세팅
  .gitignore
  craco.config.js
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/API/comment/client.ts
  src/API/comment/commentAPI.ts
  src/API/comment/index.ts
  src/API/index.ts
  src/components/detail/CommentsBox.tsx
  src/components/detail/index.ts
  src/components/search/index.ts
  src/pages/DetailPage.tsx
  src/types/comment.ts
  src/types/index.ts
  tsconfig.paths.json
Labels: ⚙️설정

#44 ✨ feat: 댓글 CRD 기능 구현
  src/API/comment/commentAPI.ts
  src/components/detail/CommentsBox.tsx
  src/styles/global.ts
  src/types/comment.ts
Labels: ✨기능 추가

#47 🎨 style: 댓글 기능 스타일링 추가
  src/API/comment/commentAPI.ts
  src/components/common/CommonHeader.tsx
  src/components/detail/CommentsBox.tsx
  src/components/detail/DetailMainContent.tsx
  src/components/icons/CommonArrow.tsx
  src/components/icons/CommonXBtn.tsx
  src/pages/DetailPage.tsx
  src/styles/contentStyle.ts
  src/styles/theme.ts
  src/types/comment.ts
Labels: 🎨HTML/CSS

#48 ✨ feat: 댓글 기능 삭제 modal 추가 및 다크모드 적용
  craco.config.js
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/atom/index.ts
  src/atom/modalState.ts
  src/atom/themeState.tsx
  src/components/common/CommonFooter.tsx
  src/components/common/CommonHeader.tsx
  src/components/common/DarkModeButton.tsx
  src/components/common/index.ts
  src/components/detail/CommentsBox.tsx
  src/components/detail/DetailRelatedList.tsx
  src/components/icons/CommonArrow.tsx
  src/components/icons/CommonLogo.tsx
  src/components/icons/CommonSearch.tsx
  src/components/icons/CommonSocial.tsx
  src/components/icons/CommonXBtn.tsx
  src/components/icons/MoonIcon.tsx
  src/components/icons/SunIcon.tsx
  src/components/icons/index.ts
  src/components/main/MainThumbnail.tsx
  src/components/modal/Modal.tsx
  src/components/modal/Portal.ts
  src/hooks/index.ts
  src/hooks/useModal.ts
  src/index.tsx
  src/styles/contentStyle.ts
  src/styles/global.ts
  src/styles/theme.ts
  src/types/comment.ts
  tsconfig.json
  tsconfig.paths.json
Labels: ✨기능 추가, 🎨HTML/CSS

#50 Feat/comment
  craco.config.js
  package-lock.json
  package.json
  public/index.html
  src/API/comment/commentAPI.ts
  src/App.tsx
  src/atom/index.ts
  src/atom/modalState.ts
  src/atom/themeState.tsx
  src/components/ErrorComponent.tsx
  src/components/common/CommonFooter.tsx
  src/components/common/CommonHeader.tsx
  src/components/common/CommonTopButton.tsx
  src/components/common/DarkModeButton.tsx
  src/components/common/index.ts
  src/components/detail/CommentsBox.tsx
  src/components/detail/DetailMainContent.tsx
  src/components/detail/DetailRelatedList.tsx
  src/components/icons/CommonArrow.tsx
  src/components/icons/CommonLogo.tsx
  src/components/icons/CommonPlayLogo.tsx
  src/components/icons/CommonSearch.tsx
  src/components/icons/CommonSocial.tsx
  src/components/icons/CommonXBtn.tsx
  src/components/icons/MoonIcon.tsx
  src/components/icons/SunIcon.tsx
  src/components/icons/index.ts
  src/components/main/MainThumbnail.tsx
  src/components/modal/Modal.tsx
  src/components/modal/Portal.ts
  src/components/search/IsNotSearched.tsx
  src/components/search/SearchContent.tsx
  src/hooks/index.ts
  src/hooks/useModal.ts
  src/index.tsx
  src/pages/DetailPage.tsx
  src/pages/SearchPage.tsx
  src/styles/contentStyle.ts
  src/styles/global.ts
  src/styles/theme.ts
  src/types/comment.ts
  src/utils/getRandomColor.ts
  src/utils/index.ts
  tsconfig.json
  tsconfig.paths.json
Labels: 🎨HTML/CSS

#52 ⚙️ config: axios 설치
  .gitignore
  package-lock.json
  package.json
  src/API/axios.ts
  src/API/index.ts
  src/pages/MainPage.tsx
  src/pages/Router.tsx
  src/utils/index.ts
  src/utils/isProduction.ts
Labels: ⚙️설정

#56 ✨ feat: 상세페이지 youtubeAPI 연결 및 TanStack query 적용
  craco.config.js
  package-lock.json
  package.json
  src/API/index.ts
  src/API/youtube/detail.ts
  src/API/youtube/index.ts
  src/components/detail/CommentsBox.tsx
  src/components/detail/DetailMainContent.tsx
  src/components/detail/DetailRelatedList.tsx
  src/index.tsx
  src/pages/DetailPage.tsx
  src/pages/Router.tsx
  src/types/video.ts
  tsconfig.paths.json
Labels: ⚙️설정, ♻️리팩토링

#63 ✨ feat: searchPage YoutubeAPI TanStack Query 적용 및 무한스크롤 구현
  src/API/youtube/index.ts
  src/API/youtube/search.ts
  src/components/common/CommonHeader.tsx
  src/components/search/SearchContent.tsx
  src/components/search/SearchContentCard.tsx
  src/components/search/index.ts
  src/hooks/index.ts
  src/hooks/useObserver.ts
  src/pages/SearchPage.tsx
  src/styles/contentStyle.ts
Labels: ✨기능 추가, ♻️리팩토링

#65 Feat/main infinite scroll
  package-lock.json
  package.json
  src/API/axios.ts
  src/API/youtube/index.ts
  src/API/youtube/youtubeAPIs.ts
  src/atom/themeState.tsx
  src/components/common/CommonHeader.tsx
  src/components/common/DarkModeButton.tsx
  src/components/detail/CommentsBox.tsx
  src/components/detail/DetailRelatedList.tsx
  src/components/icons/CommonSearch.tsx
  src/components/icons/Spinner.tsx
  src/components/icons/index.ts
  src/components/main/MainContent.tsx
  src/components/main/MainThumbnail.tsx
  src/components/modal/Modal.tsx
  src/components/search/IsNotSearched.tsx
  src/constants/commentText.ts
  src/constants/index.ts
  src/constants/isNotSearchText.ts
  src/index.tsx
  src/pages/MainPage.tsx
  src/pages/Router.tsx
  src/setupTests.ts
  src/styles/global.ts
  src/styles/theme.ts
  src/types/video.ts
Labels: ✨기능 추가, ♻️리팩토링

#68 🐛 fix: 서치 페이지 검색 이슈 해결 및 메인 페이지 패칭 코드 수정
  src/API/youtube/detail.ts
  src/API/youtube/search.ts
  src/API/youtube/youtubeAPIs.ts
  src/components/detail/DetailMainContent.tsx
  src/components/detail/DetailRelatedList.tsx
  src/components/icons/Spinner.tsx
  src/components/main/ContentCard.tsx
  src/components/main/MainContent.tsx
  src/components/main/MainThumbnail.tsx
  src/index.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/pages/SearchPage.tsx
  src/styles/contentStyle.ts
  src/utils/index.ts
  src/utils/toYYMMDDSplitedByDot.ts
Labels: 🐞버그 수정

#69 🐛 fix: 특수문자 인코딩 디코딩 문제 해결
  src/API/youtube/search.ts
  src/components/common/CommonHeader.tsx
  src/components/main/ContentCard.tsx
  src/components/search/SearchContentCard.tsx
  src/utils/decodeHTMLEntities.ts
  src/utils/index.ts
Labels: 🐞버그 수정

#71 최종 제출용
  README.md
  src/components/ErrorComponent.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/ScrollTopAnchor.tsx
  src/components/common/index.ts
  src/components/icons/index.ts
  src/components/main/MainBanner.tsx
  src/components/main/MainContent.tsx
  src/components/main/index.ts
  src/components/modal/Modal.tsx
  src/components/search/SearchContentCard.tsx
  src/index.tsx
  src/pages/DetailPage.tsx
  src/pages/Layout.tsx
  src/pages/MainPage.tsx
  src/pages/SearchPage.tsx
  src/styles/theme.ts
Labels: 🌎배포

#73 ✨ feat: 최근 검색어 기능 추가 및 리드미 수정 #72
  README.md
  src/components/common/Header.tsx
  src/components/detail/CommentsBox.tsx
  src/components/icons/CommonXBtn.tsx
Labels: ✨기능 추가, 📜문서

#74 develop => main 메인 브랜치 변경
  README.md
  craco.config.js
  package-lock.json
  package.json
  src/API/axios.ts
  src/API/index.ts
  src/API/youtube/detail.ts
  src/API/youtube/index.ts
  src/API/youtube/search.ts
  src/API/youtube/youtubeAPIs.ts
  src/atom/themeState.tsx
  src/components/ErrorComponent.tsx
  src/components/common/CommonHeader.tsx
  src/components/common/DarkModeButton.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/ScrollTopAnchor.tsx
  src/components/common/index.ts
  src/components/detail/CommentsBox.tsx
  src/components/detail/DetailMainContent.tsx
  src/components/detail/DetailRelatedList.tsx
  src/components/icons/CommonSearch.tsx
  src/components/icons/CommonXBtn.tsx
  src/components/icons/Spinner.tsx
  src/components/icons/index.ts
  src/components/main/ContentCard.tsx
  src/components/main/MainBanner.tsx
  src/components/main/MainContent.tsx
  src/components/main/MainThumbnail.tsx
  src/components/main/index.ts
  src/components/modal/Modal.tsx
  src/components/search/IsNotSearched.tsx
  src/components/search/SearchContent.tsx
  src/components/search/SearchContentCard.tsx
  src/components/search/index.ts
  src/constants/commentText.ts
  src/constants/index.ts
  src/constants/isNotSearchText.ts
  src/hooks/index.ts
  src/hooks/useObserver.ts
  src/index.tsx
  src/pages/DetailPage.tsx
  src/pages/Layout.tsx
  src/pages/MainPage.tsx
  src/pages/Router.tsx
  src/pages/SearchPage.tsx
  src/setupTests.ts
  src/styles/contentStyle.ts
  src/styles/global.ts
  src/styles/theme.ts
  src/types/video.ts
  src/utils/decodeHTMLEntities.ts
  src/utils/index.ts
  src/utils/toYYMMDDSplitedByDot.ts
  tsconfig.paths.json
Labels: ⚙️설정
